### PR TITLE
Rearchitected Project

### PR DESCRIPTION
**Pull request by RT5Phantom**
- Added Maven, in order to help build project easier
- Restructured Package structure, in order to conform to Java standards

### CODE REVIEW

**Comment by gvk** [comment]
I get the space/tab fixes. Great for consistency. 👍

Adding a gitignore for a single file project seems quite unnecessary...

Why use Maven for this project? What are the benefits? The person using this should use whatever spigot-API they want. Also they can dictate how they want this plugin done themselves. 

Why do you believe that hierarchy is better?

**Comment by RT5Phantom** [comment]
> I get the space/tab fixes. Great for consistency. 👍

Cool, glad you liked that!
<br />

> Adding a gitignore for a single file project seems quite unnecessary...

I added it to my pull request because it makes it easier for other developers to contribute to this project. With the file, Git will not send exported executables and IDE configuration files to the repository. If these files are sent it makes it harder for others to contribute to the project, because it will mess up their IDE's configurations or add unnecessarily bloat to the project when people submit a pull request. 
<br />

> Why use Maven for this project? What are the benefits? The person using this should use whatever spigot-API they want. Also they can dictate how they want this plugin done themselves.

The addition of Maven allows the project to be built and exported faster. With the Pom.xml file provided with Maven, people can more easily switch which version or branch of the Spigot-API. I believe that Maven will allow people to more easily work with this plugin and configure the setup/output of the plugin.
<br />

> Why do you believe that hierarchy is better?

I changed the hierarchy to reflect Java standards. It is not really a change that would make the project run faster or better per say, however it will help future developers who seek to use your projects in the future. 

Currently, if someone imports a utility from this project, they would **import gvk.util.***. However, if that developer is also using another plugin developed by you that also has a utility package, they would get a naming conflict as both project packages are rooted from **gvk.util**.

**Comment by RT5Phantom** [comment]
I did not think that you would actually look at my pull request for my changes, so thank you for taking the time. 

I run a server and had been looking for some sort of hibernation plugin, however there was only one or two and they did not have a lot of downloads as well as being closed source. This project pulled up on my search engine and I thought it was really well put together. I saw that the project did not necessarily conform to Java standards, so I wanted to try to contribute to the project and help if possible.

If you do not like the changes, that's okay with me. I was just trying to help you slightly improve the project and make it easier for others to access.

**Comment by xism4** [comment]
> I get the space/tab fixes. Great for consistency. 👍
> 
> Adding a gitignore for a single file project seems quite unnecessary...
> 
> Why use Maven for this project? What are the benefits? The person using this should use whatever spigot-API they want. Also they can dictate how they want this plugin done themselves.
> 
> Why do you believe that hierarchy is better?

Gitignore is good tho, any developer that wants to PR will commit all he's ide stuff

**Review by BijjuXD — APPROVED** [review]

**Comment by gvk** [comment]
Wait, how does github work?? What does approved mean? And why can bijju089 do that?

**Comment by xism4** [comment]
> Wait, how does github work?? What does approved mean? And why can bijju089 do that?

It means you see fine the pull request, probably an "opinion" system. Some times is required to merge it.

**Review by xism4 — APPROVED** [review]

**Comment by RT5Phantom** [comment]
I believe this is just a system in GitHub which allows people to voice their approval of a pull request to the owner of a repo without actually merging the changes

**Pull request closed without merging**
